/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameMetadata = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const ScoreEntry = IDL.Record({
  'score' : IDL.Int,
  'timestamp' : Time,
  'playerName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addGame' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getGameMetadata' : IDL.Func([], [IDL.Vec(GameMetadata)], ['query']),
  'getTopScores' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(ScoreEntry)],
      ['query'],
    ),
  'getTotalPlays' : IDL.Func([IDL.Text], [IDL.Int], ['query']),
  'submitScore' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameMetadata = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const ScoreEntry = IDL.Record({
    'score' : IDL.Int,
    'timestamp' : Time,
    'playerName' : IDL.Text,
  });
  
  return IDL.Service({
    'addGame' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getGameMetadata' : IDL.Func([], [IDL.Vec(GameMetadata)], ['query']),
    'getTopScores' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(ScoreEntry)],
        ['query'],
      ),
    'getTotalPlays' : IDL.Func([IDL.Text], [IDL.Int], ['query']),
    'submitScore' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };