/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'username' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface GameMetadata {
  'name' : string,
  'description' : string,
  'category' : string,
}
export interface ScoreEntry {
  'score' : bigint,
  'timestamp' : Time,
  'playerName' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addGame' : ActorMethod<[string, string, string], undefined>,
  'getGameMetadata' : ActorMethod<[], Array<GameMetadata>>,
  'getRecentMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getTopScores' : ActorMethod<[string, bigint], Array<ScoreEntry>>,
  'getTotalPlays' : ActorMethod<[string], bigint>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'submitScore' : ActorMethod<[string, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];